language: node_js
node_js: 8

cache:
  yarn: true

notifications:
  email: false

deploy:
  provider: npm
  email:
    secure: Yk4zOx1TVxv943zNOTgzkSw5wmgceWInmhJCE2p23V4gtPxGx8SRy7njqvW5vAPpepyXHiuKf/9e4h6omIrDHw/ueGIFFPDM3dyLWQtBRklTGsjXwoLjlWX8+iR4mzWI0McEyVgLxtZZezPsdyhRoxV+k2RpOjoVy1Ohua4T3diRO8DPTSG4iGNZ9TuiKzqulmZuvBveYUiZ+hHMD3kEzyC5ZvDSxd94XlkreMKSS36SnKVTBNcIkAZMIZEA6V6CJuDHzOu7BVBqQG2n5DVQAwjfBCgMKiUS/uqzzpMhA6IkgwGYxUhHsygdajbxdwsGwS7aqvqHP9fIZhHmZ0jTYdNPAM9XIqRGM0mTvif+ptxdiYIatxXz4zgLplh+8BsgxzvS4cVZJJrVQrELgZVskvxbtbtSs/vqhJ+6ZWVCplg0zCeP5lqNskXQ7b9AH0IR1qUYKDYbD3c7ltQGs66qMzo+NZqFHhSHzdOd/GX/vdleHQY4OYKD0SXxkbFBmDOHMho9BlDH/TaXYYZWDl0l7wFiyjUmyGW6iQqWo77YfWGIizCuZRHjWQGJtF+Oa6R17UnYiyWL1OiPlv3LWD4uYnWbQ5TYyQntmsqu9yojOv1lhQm5PS8VXYS6s57RVluZZC9rUnHo9tC/RzFnpgKVITk1PBfiOYxTl2vyeOJhBc4=
  api_key:
    secure: UbOUXWz8z7CoeDptREO4m2GnLnZvpp0gRpsO6w1ivPwp65VEG+TRwBofoGqG0779oOGdaR29u9+u4WrFavOy/sEgLmzLW8hZUBEc/9pnSYL4vKvfUEVKjYHuuEzLC8GXIFMcVnW4SLF7vIuNRGQ7Rdn/mNMQLMLPu0pZrDj5MmmE/7tYg06jP1SQ0NDwbMK2v+JFdWEEgIhs7idaKaPW1Y7Hir8D3NcR+FVOl3NeTibrEeSOBX876y0N0PRPeUxI38f/DWAVmWzmdzZXfNezP0YcV0JW4VJBIJBZKsK3RSwrqfQyN+RthDNg61wki/5tdu60LSw8HrVaqtGSjph5AMTdO4Ozf77Bww+OcI4bJ4chVciDhs69NaIYIuTJ+EZlNwMUci0i+CkK7y4Ae0DTt5x0niOzWUk046iwz+NfZgNtCaDL+HE7VDfv7yZgOFevIHiZ5Vh7BR4jzBP0zlMdlpdVbValF8lnmFM5f7+lJFnWRdkNnkoxIfZbUDXt9TsK7lwrCYVcIHjkWL4Cr0mif4Se+Y7X+vsqWMrMqY1axrQEiY5PZLt7MQs4jxyJvlD5Np23PxZ6qJq1aNRo0scepPpaGNGQY4tyH09HrguY9xsMc8wLISmhPnDjSqGnSHSitCHjOs58CmoXG4BN2tCHqBBv4+ABRXDXfzyGo0+xr60=
  on:
    tags: true
    repo: thelounge/thelounge-theme-crypto
    branch: master
