language: node_js
node_js: 8

cache:
  yarn: true

notifications:
  email: false

deploy:
  provider: npm
  email:
    secure: NkBoGEy6revCOtvjf2SlztjHIjdcJhJiXP6ImGQfL/uDAYasa80dFr37hB9kwaan5CaP/7JWytUo2r1bXysJpwsxvyECYVGBib4iSojrVVmnNSLawQ+HYsJrx8ACL0AHslyyQhGpCwUJBnu6zmEzbwdS+rPXGjYpmFMwilVvZcfYtBtdnGCH9XK3Ldmz2n975DO0C2Mswxr0TDPywNUOB3HTo5rk2V1ZURP9FEe5nX2wbqXbiRlaED4G/4DNqTMjUTuRWuh9yKoGEkCIas36Kw2j0gtP6yBYxUu9+nu8n271q3gzdPkHRUFExXZRh+UAK+Rp/ixvkOc/QCdrnmGY5d/vT/qvaBg9J1bfc2rDN7KFcbxg3sAq6scj9VsyMmI89/w0JSQOL3yO7XYH3EbqkyceNHrIipWqPY0nz48SzAySYe3ihvLCw+Gx7Pzn5rU6AypRHSkhio5bosKvY9lTqCXVNaYw43xRT9OSaXecmzO+ZtVyPi/05uYoiajHenKEqB/xrX5L2Zd4oBoK7dSF37cv3IlgqeWs6Yb71o1SrRP6Twaw3F/o+24/iCb8gqTK1aXoPZcwYl1mWgD2n+VGqS1RsL0CLU8FCABQa7v7pCaEftmdbA0aSQTPVyL9ZmbGuNHBowJ3vb4JW+9dgnatEesYK1tsqCDuo4zsNef8f30=
  api_key:
    secure: CpAHLgRR++RERzoOOV22UVAWlc3/gGnUI6rrgPKJB832K4gmETV1z0/ixUEdnPVzJ3ePqSAbr2rePIR4RxzjscxVgHigLfKptj7g8dZY1JLNDgKZw2V5+A36jngLc/Fs4NmW7y5wVxWANvhA/foi5u4NRk2d9i5kQlgkSzAYzX36GMEEdDrsFArWXcUfausUUqiF5EYO5Fy0YPfYf0Iw4NvBnPyd3QSwk21nStb74Ks7r314NH2CkFfUqJCP/7JyvteW85NVNLHM+rmiKdzSN9ZyRzOdBWUCr0mcb3YI66pyHUDPGvMpQVQ742RTqHBronHs9v0NGqeRvbIdHm4QkMnmRWdaxcE7olkFejn9XFqtBOVZYMfTCrHctz4TsCeuPRA3CuGeV8IjIKiHYCWOiO3KoU838ZO8X5pNMio4VDRPgnRMjvDBmx8YiOPDB+01lghsajZWzxa/IuXxHRL//Rd27FG1iUSm84cfoxSBC0tVNcPK+V6oFB/Ok1fEo13pGSbgYVgR7o27rV3nJ1g7voWfY/C9TAuuH7CDLUfVwPbTQjO2XMvjamp2uFy9G2MUkyFGa73QpLLJmTk9hA+AgL+nGGEm6UiX8uZaDyyTetkdCTKmFmm6siky+YiCNzzwd3LniXZfrHdcCs3qcHoXWlL6xXJ4QXAXTH91Pf4yRVQ=
  on:
    tags: true
    repo: thelounge/thelounge-theme-crypto
    branch: master
